Resources:
  SalesSyncApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/bundle           # <— pre-bundled output folder
      Handler: app.lambdaHandler     # <— bundle/app.js exports lambdaHandler
      Runtime: nodejs22.x
      Architectures: [ x86_64 ]
      Events:
        ApiRouter:
          Type: Api
          Properties:
            RestApiId: !Ref SalesSyncApi
            Path: /auth/{proxy+}
            Method: ANY

  WorkspaceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: workspace/bundle      # <— pre-bundled output folder
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures: [ x86_64 ]
      Events:
        ApiRouter:
          Type: Api
          Properties:
            RestApiId: !Ref SalesSyncApi
            Path: /workspace/{proxy+}
            Method: ANY

  WorkspaceDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: workspace/bundle      # <— pre-bundled output folder
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures: [ x86_64 ]
      Events:
        ApiRouter:
          Type: Api
          Properties:
            RestApiId: !Ref SalesSyncApi
            Path: /workspace
            Method: ANY
